/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SegmentosRouteImport } from './routes/segmentos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as ComoEscolherRouteImport } from './routes/como-escolher'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SegmentosIndexRouteImport } from './routes/segmentos.index'
import { Route as SegmentosRevendedoresRouteImport } from './routes/segmentos.revendedores'
import { Route as SegmentosIndustriasRouteImport } from './routes/segmentos.industrias'
import { Route as SegmentosEnergiaSolarRouteImport } from './routes/segmentos.energia-solar'
import { Route as SegmentosConstrucaoCivilRouteImport } from './routes/segmentos.construcao-civil'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosRoute = SegmentosRouteImport.update({
  id: '/segmentos',
  path: '/segmentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoEscolherRoute = ComoEscolherRouteImport.update({
  id: '/como-escolher',
  path: '/como-escolher',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosIndexRoute = SegmentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SegmentosRoute,
} as any)
const SegmentosRevendedoresRoute = SegmentosRevendedoresRouteImport.update({
  id: '/revendedores',
  path: '/revendedores',
  getParentRoute: () => SegmentosRoute,
} as any)
const SegmentosIndustriasRoute = SegmentosIndustriasRouteImport.update({
  id: '/industrias',
  path: '/industrias',
  getParentRoute: () => SegmentosRoute,
} as any)
const SegmentosEnergiaSolarRoute = SegmentosEnergiaSolarRouteImport.update({
  id: '/energia-solar',
  path: '/energia-solar',
  getParentRoute: () => SegmentosRoute,
} as any)
const SegmentosConstrucaoCivilRoute =
  SegmentosConstrucaoCivilRouteImport.update({
    id: '/construcao-civil',
    path: '/construcao-civil',
    getParentRoute: () => SegmentosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-escolher': typeof ComoEscolherRoute
  '/orcamento': typeof OrcamentoRoute
  '/produtos': typeof ProdutosRoute
  '/segmentos': typeof SegmentosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/segmentos/construcao-civil': typeof SegmentosConstrucaoCivilRoute
  '/segmentos/energia-solar': typeof SegmentosEnergiaSolarRoute
  '/segmentos/industrias': typeof SegmentosIndustriasRoute
  '/segmentos/revendedores': typeof SegmentosRevendedoresRoute
  '/segmentos/': typeof SegmentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-escolher': typeof ComoEscolherRoute
  '/orcamento': typeof OrcamentoRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/segmentos/construcao-civil': typeof SegmentosConstrucaoCivilRoute
  '/segmentos/energia-solar': typeof SegmentosEnergiaSolarRoute
  '/segmentos/industrias': typeof SegmentosIndustriasRoute
  '/segmentos/revendedores': typeof SegmentosRevendedoresRoute
  '/segmentos': typeof SegmentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-escolher': typeof ComoEscolherRoute
  '/orcamento': typeof OrcamentoRoute
  '/produtos': typeof ProdutosRoute
  '/segmentos': typeof SegmentosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/segmentos/construcao-civil': typeof SegmentosConstrucaoCivilRoute
  '/segmentos/energia-solar': typeof SegmentosEnergiaSolarRoute
  '/segmentos/industrias': typeof SegmentosIndustriasRoute
  '/segmentos/revendedores': typeof SegmentosRevendedoresRoute
  '/segmentos/': typeof SegmentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-escolher'
    | '/orcamento'
    | '/produtos'
    | '/segmentos'
    | '/sobre'
    | '/segmentos/construcao-civil'
    | '/segmentos/energia-solar'
    | '/segmentos/industrias'
    | '/segmentos/revendedores'
    | '/segmentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-escolher'
    | '/orcamento'
    | '/produtos'
    | '/sobre'
    | '/segmentos/construcao-civil'
    | '/segmentos/energia-solar'
    | '/segmentos/industrias'
    | '/segmentos/revendedores'
    | '/segmentos'
  id:
    | '__root__'
    | '/'
    | '/como-escolher'
    | '/orcamento'
    | '/produtos'
    | '/segmentos'
    | '/sobre'
    | '/segmentos/construcao-civil'
    | '/segmentos/energia-solar'
    | '/segmentos/industrias'
    | '/segmentos/revendedores'
    | '/segmentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoEscolherRoute: typeof ComoEscolherRoute
  OrcamentoRoute: typeof OrcamentoRoute
  ProdutosRoute: typeof ProdutosRoute
  SegmentosRoute: typeof SegmentosRouteWithChildren
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos': {
      id: '/segmentos'
      path: '/segmentos'
      fullPath: '/segmentos'
      preLoaderRoute: typeof SegmentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-escolher': {
      id: '/como-escolher'
      path: '/como-escolher'
      fullPath: '/como-escolher'
      preLoaderRoute: typeof ComoEscolherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/': {
      id: '/segmentos/'
      path: '/'
      fullPath: '/segmentos/'
      preLoaderRoute: typeof SegmentosIndexRouteImport
      parentRoute: typeof SegmentosRoute
    }
    '/segmentos/revendedores': {
      id: '/segmentos/revendedores'
      path: '/revendedores'
      fullPath: '/segmentos/revendedores'
      preLoaderRoute: typeof SegmentosRevendedoresRouteImport
      parentRoute: typeof SegmentosRoute
    }
    '/segmentos/industrias': {
      id: '/segmentos/industrias'
      path: '/industrias'
      fullPath: '/segmentos/industrias'
      preLoaderRoute: typeof SegmentosIndustriasRouteImport
      parentRoute: typeof SegmentosRoute
    }
    '/segmentos/energia-solar': {
      id: '/segmentos/energia-solar'
      path: '/energia-solar'
      fullPath: '/segmentos/energia-solar'
      preLoaderRoute: typeof SegmentosEnergiaSolarRouteImport
      parentRoute: typeof SegmentosRoute
    }
    '/segmentos/construcao-civil': {
      id: '/segmentos/construcao-civil'
      path: '/construcao-civil'
      fullPath: '/segmentos/construcao-civil'
      preLoaderRoute: typeof SegmentosConstrucaoCivilRouteImport
      parentRoute: typeof SegmentosRoute
    }
  }
}

interface SegmentosRouteChildren {
  SegmentosConstrucaoCivilRoute: typeof SegmentosConstrucaoCivilRoute
  SegmentosEnergiaSolarRoute: typeof SegmentosEnergiaSolarRoute
  SegmentosIndustriasRoute: typeof SegmentosIndustriasRoute
  SegmentosRevendedoresRoute: typeof SegmentosRevendedoresRoute
  SegmentosIndexRoute: typeof SegmentosIndexRoute
}

const SegmentosRouteChildren: SegmentosRouteChildren = {
  SegmentosConstrucaoCivilRoute: SegmentosConstrucaoCivilRoute,
  SegmentosEnergiaSolarRoute: SegmentosEnergiaSolarRoute,
  SegmentosIndustriasRoute: SegmentosIndustriasRoute,
  SegmentosRevendedoresRoute: SegmentosRevendedoresRoute,
  SegmentosIndexRoute: SegmentosIndexRoute,
}

const SegmentosRouteWithChildren = SegmentosRoute._addFileChildren(
  SegmentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoEscolherRoute: ComoEscolherRoute,
  OrcamentoRoute: OrcamentoRoute,
  ProdutosRoute: ProdutosRoute,
  SegmentosRoute: SegmentosRouteWithChildren,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
